name: Push
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build Calc.py
        run: python Calc.py

  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Tests
        run: python -m unittest test.py
  
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create and push tag
        run: |
          TAG_NAME="build_$(date +'%m%d%Y%H%M%S')"
          git tag $TAG_NAME
          git push --tags
 
  generate-artifact:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Archive
        run: |
          git fetch
          git checkout main
          zip -r main.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: main.zip

